import { Prisma, type PrismaClient } from "@/src/generated/prisma/client";
import { ProvisioningError, type ProvisioningRecord } from "@/src/application/auth/operator-provisioning";

export class PrismaOperatorProvisioningPersistence {
  constructor(private readonly prisma: PrismaClient) {}

  async create(input: ProvisioningRecord): Promise<void> {
    try {
      await this.prisma.$transaction(async tx => {
        await createControlledCustomer(tx, input);
      });
    } catch (error) {
      if (error instanceof ProvisioningError) throw error;
      if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new ProvisioningError("PROVISIONING_CONFLICT");
      throw new ProvisioningError("OPERATIONAL_FAILURE");
    }
  }
}

// Shared transaction boundary for CLI provisioning and request approval.
export async function createControlledCustomer(tx: Prisma.TransactionClient, input: ProvisioningRecord, profile?: { readonly contactName: string; readonly locale: string }) {
  if (await tx.user.findUnique({ where: { email: input.email }, select: { id: true } })) {
    throw new ProvisioningError("EXISTING_BUSINESS_EMAIL");
  }
  // New aggregates only. UUID defaults are generated by Prisma, never accepted from the operator.
  const organization = await tx.organization.create({ data: { displayName: input.organizationDisplayName, status: "ACTIVE", ...(profile ? { defaultLocale: profile.locale } : {}) }, select: { id: true } });
  const user = await tx.user.create({ data: { email: input.email, ...(profile ? { displayName: profile.contactName, preferredLocale: profile.locale } : {}) }, select: { id: true } });
  await tx.membership.create({ data: { organizationId: organization.id, userId: user.id, role: input.role, status: "ACTIVE" }, select: { id: true } });
  const activation = await tx.accountActivationIntent.create({ data: {
    userId: user.id, provider: "BETTER_AUTH", status: "ISSUED",
    tokenDigest: input.tokenDigest, intendedEmailDigest: input.intendedEmailDigest,
    createdAt: input.issuedAt, expiresAt: input.expiresAt,
  }, select: { id: true } });
  await tx.auditLog.create({ data: {
    organizationId: organization.id, actorId: null,
    action: "CONTROLLED_CUSTOMER_PROVISIONED", entityType: "ORGANIZATION", entityId: organization.id,
    summary: "Controlled customer provisioned.", metadata: { role: input.role }, occurredAt: input.issuedAt,
  }, select: { id: true } });
  return { organizationId: organization.id, userId: user.id, activationId: activation.id };
}
