import type { ReminderDecision } from "@/src/application/subscriptions/reminders";
import { isPassveroLocale } from "@/src/domain/values/passvero-locale";
import { COMMERCIAL_TIME_ZONE } from "@/src/application/subscriptions/calendar";

const copy = {
  hr: { subject: "Podsjetnik o pretplati", public: "Rok javne dostupnosti DPP-a", trial: "Probno razdoblje", plan: "Paket", deadline: "Rok", open: "Pregled pretplate", operator: "Obavijest billing operatoru", LOCKS: "Nakon isteka izmjene sadržaja i nove objave bit će blokirane ako se pretplata ne obnovi.", LOCKED: "Razdoblje je isteklo. Izmjene sadržaja i nove objave su blokirane; privatni pregled i dopušteni izvoz ostaju dostupni prema ugovorenoj politici čuvanja.", CONDITIONAL: "Budući manji paket još ovisi o provjeri kvota. Nastavak prava nije zajamčen; provjerite uvjete promjene paketa.", GAP: "Potvrđeno je buduće razdoblje. Do njegova početka nakon navedenog isteka izmjene sadržaja i nove objave nisu dopuštene.", PUBLIC_ENDS: "Ako se pretplata ne obnovi, na navedeni rok prestaje produžena javna dostupnost samo podobnih dobrovoljnih (VOLUNTARY) objava. Obvezni i nerazjašnjeni DPP-ovi nisu obuhvaćeni ovim gašenjem. Nema automatskog brisanja podataka.", next: "Početak budućeg razdoblja", count: "Podobne dobrovoljne objave" },
  sr: { subject: "Podsetnik o pretplati", public: "Rok javne dostupnosti DPP-a", trial: "Probni period", plan: "Paket", deadline: "Rok", open: "Pregled pretplate", operator: "Obaveštenje billing operatoru", LOCKS: "Nakon isteka izmene sadržaja i nove objave biće blokirane ako se pretplata ne obnovi.", LOCKED: "Period je istekao. Izmene sadržaja i nove objave su blokirane; privatni pregled i dozvoljeni izvoz ostaju dostupni prema ugovorenoj politici čuvanja.", CONDITIONAL: "Budući manji paket još zavisi od provere kvota. Nastavak prava nije zajamčen; proverite uslove promene paketa.", GAP: "Potvrđen je budući period. Do njegovog početka nakon navedenog isteka izmene sadržaja i nove objave nisu dozvoljene.", PUBLIC_ENDS: "Ako se pretplata ne obnovi, na navedeni rok prestaje produžena javna dostupnost samo podobnih dobrovoljnih (VOLUNTARY) objava. Obavezni i nerazjašnjeni DPP-ovi nisu obuhvaćeni ovim gašenjem. Nema automatskog brisanja podataka.", next: "Početak budućeg perioda", count: "Podobne dobrovoljne objave" },
  en: { subject: "Subscription reminder", public: "DPP public availability deadline", trial: "Trial", plan: "Plan", deadline: "Deadline", open: "View subscription", operator: "Billing operator notification", LOCKS: "Content changes and new publications will be blocked after expiry unless the subscription is renewed.", LOCKED: "The period has expired. Content changes and new publications are blocked; private viewing and permitted exports remain available under the agreed retention policy.", CONDITIONAL: "The future lower plan still requires a quota check. Continued access is not guaranteed; review the plan change conditions.", GAP: "A future period is confirmed. Content changes and new publications are unavailable between the stated expiry and that period's start.", PUBLIC_ENDS: "Unless the subscription is renewed, extended public availability ends at this deadline only for eligible voluntary (VOLUNTARY) publications. Mandatory and unresolved DPPs are excluded from this shutdown. Data is not automatically deleted.", next: "Future period starts", count: "Eligible voluntary publications" },
  de: { subject: "Erinnerung an Ihr Abonnement", public: "Frist für die öffentliche DPP-Verfügbarkeit", trial: "Testzeitraum", plan: "Paket", deadline: "Frist", open: "Abonnement ansehen", operator: "Benachrichtigung für die Abrechnungsverwaltung", LOCKS: "Nach Ablauf werden Inhaltsänderungen und neue Veröffentlichungen gesperrt, sofern das Abonnement nicht verlängert wird.", LOCKED: "Der Zeitraum ist abgelaufen. Inhaltsänderungen und neue Veröffentlichungen sind gesperrt; private Ansicht und zulässige Exporte bleiben gemäß der vereinbarten Aufbewahrungsregelung verfügbar.", CONDITIONAL: "Das künftige kleinere Paket erfordert noch eine Kontingentprüfung. Der weitere Zugang ist nicht garantiert; prüfen Sie die Bedingungen des Paketwechsels.", GAP: "Ein künftiger Zeitraum ist bestätigt. Zwischen dem genannten Ablauf und dessen Beginn sind Inhaltsänderungen und neue Veröffentlichungen nicht verfügbar.", PUBLIC_ENDS: "Ohne Verlängerung endet zu dieser Frist die verlängerte öffentliche Verfügbarkeit ausschließlich für berechtigte freiwillige (VOLUNTARY) Veröffentlichungen. Verpflichtende und ungeklärte DPPs sind von dieser Abschaltung ausgenommen. Daten werden nicht automatisch gelöscht.", next: "Beginn des künftigen Zeitraums", count: "Berechtigte freiwillige Veröffentlichungen" },
  sl: { subject: "Opomnik o naročnini", public: "Rok javne dostopnosti DPP", trial: "Preizkusno obdobje", plan: "Paket", deadline: "Rok", open: "Pregled naročnine", operator: "Obvestilo skrbniku obračunavanja", LOCKS: "Po izteku bodo spremembe vsebine in nove objave blokirane, če naročnina ne bo podaljšana.", LOCKED: "Obdobje je poteklo. Spremembe vsebine in nove objave so blokirane; zasebni ogled in dovoljeni izvozi ostajajo na voljo v skladu z dogovorjeno politiko hrambe.", CONDITIONAL: "Prihodnji manjši paket še zahteva preverjanje kvot. Nadaljnji dostop ni zagotovljen; preverite pogoje spremembe paketa.", GAP: "Prihodnje obdobje je potrjeno. Med navedenim iztekom in začetkom tega obdobja spremembe vsebine in nove objave niso na voljo.", PUBLIC_ENDS: "Če naročnina ni podaljšana, se ob tem roku konča podaljšana javna dostopnost samo upravičenih prostovoljnih (VOLUNTARY) objav. Obvezni in nerazjasnjeni DPP niso vključeni v ta izklop. Podatki se ne izbrišejo samodejno.", next: "Začetek prihodnjega obdobja", count: "Upravičene prostovoljne objave" },
  pl: { subject: "Przypomnienie o subskrypcji", public: "Termin publicznej dostępności DPP", trial: "Okres próbny", plan: "Pakiet", deadline: "Termin", open: "Zobacz subskrypcję", operator: "Powiadomienie dla operatora rozliczeń", LOCKS: "Po wygaśnięciu zmiany treści i nowe publikacje zostaną zablokowane, chyba że subskrypcja zostanie odnowiona.", LOCKED: "Okres wygasł. Zmiany treści i nowe publikacje są zablokowane; prywatny podgląd i dozwolony eksport pozostają dostępne zgodnie z uzgodnioną polityką przechowywania.", CONDITIONAL: "Przyszły niższy pakiet nadal wymaga sprawdzenia limitów. Dalszy dostęp nie jest gwarantowany; sprawdź warunki zmiany pakietu.", GAP: "Potwierdzono przyszły okres. Od wskazanego wygaśnięcia do początku tego okresu zmiany treści i nowe publikacje są niedostępne.", PUBLIC_ENDS: "Bez odnowienia subskrypcji przedłużona publiczna dostępność zakończy się w tym terminie wyłącznie dla uprawnionych dobrowolnych (VOLUNTARY) publikacji. Obowiązkowe i nierozstrzygnięte DPP są wyłączone z tego wyłączenia. Dane nie są automatycznie usuwane.", next: "Początek przyszłego okresu", count: "Uprawnione dobrowolne publikacje" },
} as const;
const escapeHtml = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
export function renderReminderEmail(input: { organizationName: string; locale: string; decision: ReminderDecision; operator: boolean }, canonicalOrigin: string) {
  const origin = new URL(canonicalOrigin);
  if (origin.protocol !== "https:" || origin.origin !== canonicalOrigin || origin.username || origin.password) throw new Error("REMINDER_ORIGIN_INVALID");
  const locale = isPassveroLocale(input.locale) ? input.locale : "hr", language = copy[locale], decision = input.decision;
  const format = (date: Date) => `${new Intl.DateTimeFormat(locale, { timeZone: COMMERCIAL_TIME_ZONE, dateStyle: "long", timeStyle: "long" }).format(date)} (Europe/Zagreb; ${date.toISOString()})`;
  // Use the existing protected subscription flow; the organization is displayed explicitly.
  const url = `${origin.origin}${locale === "hr" ? "" : `/${locale}`}${input.operator ? "/platform/billing" : "/dashboard/subscription"}`;
  const subject = `Passvero — ${decision.kind === "SUBSCRIPTION" ? language.subject : language.public}`;
  const lines = [input.organizationName, ...(input.operator ? [language.operator] : []), `${language.plan}: ${decision.planSlug === "trial" ? language.trial : decision.planSlug}`, `${language.deadline}: ${format(decision.deadline)}`, language[decision.consequence], ...(decision.nextStart ? [`${language.next}: ${format(decision.nextStart)}`] : []), ...(decision.kind === "PUBLIC_AVAILABILITY" ? [`${language.count}: ${decision.eligiblePublications}`] : [])];
  return { subject, text: `${lines.join("\n\n")}\n\n${language.open}: ${url}`, html: `<html lang="${locale}"><body style="margin:0;background:#f8fafc;color:#0f172a;font-family:Arial,sans-serif"><main style="max-width:600px;margin:24px auto;padding:24px;background:#fff;border:1px solid #e2e8f0;border-radius:12px"><h1 style="color:#0b1d2a;font-size:24px">Passvero</h1>${lines.map(line => `<p style="line-height:1.6;overflow-wrap:anywhere">${escapeHtml(line)}</p>`).join("")}<p><a style="color:#2563eb" href="${escapeHtml(url)}">${escapeHtml(language.open)}</a></p></main></body></html>` };
}
