import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { createTestPrismaClient, requireSafeTestDatabaseConfig } from "../helpers/test-database";
import { PrismaPlatform } from "../../src/infrastructure/platform/prisma-platform";
import { changePlatformGrant } from "../../src/infrastructure/platform/platform-grant";
import type { PlatformActor } from "../../src/application/platform/service";
import { PrismaBillingPersistence } from "../../src/infrastructure/persistence/prisma/prisma-billing-profile";
import { billingPermissionsForRole } from "../../src/application/permissions/billing-permissions";
const db=createTestPrismaClient(requireSafeTestDatabaseConfig(process.env));
test.after(()=>db.$disconnect());
test("explicit platform authority, isolated DB roles, bounded reads, revoke and atomic operator audit",async()=>{
 const email=`${randomUUID()}@example.invalid`;
 const user=await db.user.create({data:{email}});
 const provider=await db.authProviderUser.create({data:{id:randomUUID(),email,name:"Synthetic",emailVerified:true}});
 const identity=await db.authIdentity.create({data:{userId:user.id,provider:"BETTER_AUTH",providerSubject:provider.id}});
 const session=await db.authProviderSession.create({data:{id:randomUUID(),userId:provider.id,token:randomUUID(),expiresAt:new Date(Date.now()+3600000)}});
 const actor:PlatformActor={status:"AUTHENTICATED",currentUser:{userId:user.id},providerSession:{provider:"BETTER_AUTH",providerSessionId:session.id}};
 await db.$executeRawUnsafe('CREATE ROLE platform_business_proof NOLOGIN');
 await db.$executeRawUnsafe('CREATE ROLE platform_auth_proof NOLOGIN');
 await db.$executeRawUnsafe('CREATE ROLE platform_operator_proof NOLOGIN');
 await db.$executeRawUnsafe('GRANT USAGE ON SCHEMA public TO platform_business_proof, platform_auth_proof, platform_operator_proof');
 await db.$executeRawUnsafe('GRANT SELECT ON "User", "Membership", "Organization", "OrganizationBillingProfile", "AuthIdentity", "PlatformGrant" TO platform_business_proof, platform_operator_proof');
 await db.$executeRawUnsafe('GRANT SELECT ON "AuthProviderSession", "AuthProviderUser" TO platform_auth_proof');
 await db.$executeRawUnsafe('GRANT INSERT, UPDATE ON "PlatformGrant" TO platform_operator_proof');
 await db.$executeRawUnsafe('GRANT SELECT, INSERT ON "AuthAuditEvent" TO platform_operator_proof');
 function client(role:string){const url=new URL(process.env.TEST_DATABASE_URL!);url.searchParams.set("options",`-c role=${role}`);return createTestPrismaClient(requireSafeTestDatabaseConfig({NODE_ENV:"test",TEST_DATABASE_URL:url.toString()}));}
 const business=client("platform_business_proof"),auth=client("platform_auth_proof"),operator=client("platform_operator_proof");
 test.after(async()=>{await Promise.all([business.$disconnect(),auth.$disconnect(),operator.$disconnect()]);});
 const api=new PrismaPlatform(business,auth);
 const org=await db.organization.create({data:{displayName:"Platform synthetic 100%_literal"}});
 const other=await db.organization.create({data:{displayName:"Other synthetic"}});
 const member=await db.membership.create({data:{userId:user.id,organizationId:org.id,role:"ADMIN"}});
 for (const role of ["OWNER","ADMIN","VIEWER"] as const) {
  await db.membership.update({where:{id:member.id},data:{role}});
  assert.equal(await api.authorize(actor),false);
 }
 await db.membership.update({where:{id:member.id},data:{role:"ADMIN"}});
 await assert.rejects(db.platformGrant.create({data:{userId:randomUUID()}}));
 await assert.rejects(api.list(actor,{q:"",cursor:null}),{code:"PLATFORM_FORBIDDEN"});
 await assert.rejects(api.detail(actor,other.id),{code:"PLATFORM_FORBIDDEN"});
 await assert.rejects(business.platformGrant.create({data:{userId:user.id}}));
 const command={action:"grant",email,operator:"local-proof"};
 assert.equal((await changePlatformGrant(operator,auth,command)).status,"GRANTED");
 assert.equal((await changePlatformGrant(operator,auth,command)).status,"NO_CHANGE");
 assert.equal(await db.authAuditEvent.count({where:{userId:user.id}}),1);
 assert.equal(await api.authorize(actor),true);
 assert.equal((await api.detail(actor,other.id))?.billingProfile,null);
 const values={legalName:"PRIVATE LEGAL CANARY",addressLine1:"Test 1",addressLine2:null,city:"Test",postalCode:"00100",countryCode:"HR",billingEmail:"synthetic@example.invalid",taxIdentifier:"000123",vatIdentifier:null};
 await db.organizationBillingProfile.create({data:{organizationId:other.id,...values}});
 assert.equal((await api.list(actor,{q:"private legal",cursor:null})).items[0].id,other.id);
 assert.equal((await api.list(actor,{q:"100%_",cursor:null})).items[0].id,org.id);
 assert.equal((await api.list(actor,{q:"no-match",cursor:null})).items.length,0);
 assert.equal((await api.detail(actor,other.id))?.billingProfile?.taxIdentifier,"000123");
 const list=await api.list(actor,{q:"",cursor:null});assert.ok(!JSON.stringify(list).includes(values.legalName));assert.ok(!JSON.stringify(list).includes(email));
 await db.organization.createMany({data:Array.from({length:29},(_,i)=>({displayName:`Page ${i}`}))});
 const first=await api.list(actor,{q:"Page",cursor:null});assert.equal(first.items.length,25);assert.ok(first.nextCursor);
 const second=await api.list(actor,{q:"Page",cursor:first.nextCursor});assert.equal(second.items.length,4);assert.equal(second.nextCursor,null);assert.equal(new Set([...first.items,...second.items].map(row=>row.id)).size,29);
 const tenant=new PrismaBillingPersistence(business);
 const context={userId:user.id,organizationId:other.id,membershipId:member.id,membershipRole:"ADMIN" as const,membershipStatus:"ACTIVE" as const,permissions:billingPermissionsForRole("ADMIN"),correlationId:randomUUID()};
 await assert.rejects(tenant.get(context),{code:"FORBIDDEN"});
 assert.equal((await changePlatformGrant(operator,auth,{...command,action:"revoke"})).status,"REVOKED");
 assert.equal((await changePlatformGrant(operator,auth,{...command,action:"revoke"})).status,"NO_CHANGE");
 await assert.rejects(api.detail(actor,other.id),{code:"PLATFORM_FORBIDDEN"});
 await db.$executeRawUnsafe(`CREATE FUNCTION platform_audit_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'proof'; END $$`);
 await db.$executeRawUnsafe('CREATE TRIGGER platform_audit_fail BEFORE INSERT ON "AuthAuditEvent" FOR EACH ROW EXECUTE FUNCTION platform_audit_fail()');
 await assert.rejects(changePlatformGrant(operator,auth,command));assert.equal(await api.authorize(actor),false);
 await db.$executeRawUnsafe('DROP TRIGGER platform_audit_fail ON "AuthAuditEvent"');await db.$executeRawUnsafe('DROP FUNCTION platform_audit_fail()');
 await changePlatformGrant(operator,auth,command);
 await db.authIdentity.update({where:{id:identity.id},data:{revokedAt:new Date()}});assert.equal(await api.authorize(actor),false);
 await assert.rejects(changePlatformGrant(operator,auth,command),{code:"VERIFIED_IDENTITY_REQUIRED"});
 await db.authIdentity.update({where:{id:identity.id},data:{revokedAt:null}});
 await db.authProviderUser.update({where:{id:provider.id},data:{emailVerified:false}});assert.equal(await api.authorize(actor),false);
 await db.authProviderUser.update({where:{id:provider.id},data:{emailVerified:true}});
 await db.authProviderSession.update({where:{id:session.id},data:{expiresAt:new Date(0)}});assert.equal(await api.authorize(actor),false);
 assert.equal(await db.membership.count({where:{userId:user.id}}),1);
});
