import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { createTestPrismaClient, requireSafeTestDatabaseConfig } from "../helpers/test-database";
import { approval, createApprovedFixtures, appendApprovedRenewal, narrowApprovedScope, approvedSummary, resumeApprovedFixtures } from "../../scripts/subscription-reminders/acceptance-fixtures";
import { ReminderWorker } from "../../src/infrastructure/subscriptions/reminder-worker";
const db = createTestPrismaClient(requireSafeTestDatabaseConfig(process.env));
test.after(() => db.$disconnect());
import { createGetPublicDppService } from "../../src/application/public-dpp/get-public-dpp";
import { PrismaPublicDppPersistence } from "../../src/infrastructure/persistence/prisma/prisma-public-dpp";
const now = new Date("2026-09-30T21:00:00.000Z");
test("approved fixture sequence: expiry/grant guards, exact recipients, renewal cancellation, four dispatches and replay", async (t) => {
  t.mock.timers.enable({ apis: ["Date"], now });
  await assert.rejects(createApprovedFixtures(db, new Date(approval.expiresAt)), /APPROVAL_EXPIRED/);
  for (const person of [approval.owner, ...approval.operators]) {
    const user = await db.user.create({ data: { id: person.userId, email: person.email, preferredLocale: "hr" } });
    const provider = await db.authProviderUser.create({ data: { id: randomUUID(), email: person.email, name: "Synthetic", emailVerified: true } });
    await db.authIdentity.create({ data: { userId: user.id, provider: "BETTER_AUTH", providerSubject: provider.id } });
  }
  await assert.rejects(createApprovedFixtures(db, now));
  assert.equal(await db.organization.count(), 0);
  for (const person of approval.operators) {
    await db.platformBillingGrant.create({ data: { userId: person.userId } });
    await db.platformRegulatoryGrant.create({ data: { userId: person.userId } });
  }
  const created = await createApprovedFixtures(db, now);
  assert.equal(created.organizationIds.length, 3);
  const product = await db.product.findUniqueOrThrow({ where: { id: created.productId } });
  assert.equal((await createGetPublicDppService({ persistence: new PrismaPublicDppPersistence(db) })({ publicCode: product.publicCode, requestedLocale: "hr", acceptLanguage: null })).kind, "PUBLIC");
  assert.equal(await db.billingEmailConfirmation.count(), 0);
  assert.equal(await db.authProviderSession.count(), 0);
  await assert.rejects(createApprovedFixtures(db, now), /NO_EXISTING_CAMPAIGNS_EXPECTED/);
  await db.reminderCampaign.updateMany({ data: { enabled: false } });
  await db.reminderCampaign.update({ where: { id: approval.campaigns[0].id }, data: { dispatches: 1 } });
  await assert.rejects(resumeApprovedFixtures(db, created, now));
  assert.equal(await db.reminderCampaign.count({ where: { enabled: true } }), 0);
  await db.reminderCampaign.update({ where: { id: approval.campaigns[0].id }, data: { dispatches: 0, maxDispatches: 3 } });
  await assert.rejects(resumeApprovedFixtures(db, created, now));
  assert.equal(await db.reminderCampaign.count({ where: { enabled: true } }), 0);
  await db.reminderCampaign.update({ where: { id: approval.campaigns[0].id }, data: { maxDispatches: 2 } });
  await assert.rejects(resumeApprovedFixtures(db, created, new Date(approval.expiresAt)), /APPROVAL_EXPIRED/);
  assert.deepEqual(await resumeApprovedFixtures(db, created, now), created);
  assert.equal(await db.organization.count(), 3);
  assert.equal(await db.subscriptionPaidPeriod.count(), 1);
  const calls: Array<{ recipient: string; text: string }> = [];
  const worker = new ReminderWorker(db, db, { async send(mail) { calls.push({ recipient: mail.recipient, text: mail.text }); return { status: "ACCEPTED" }; } }, { canonicalOrigin: "https://staging.passvero.eu", runtimeEnvironment: "staging", now: () => now });
  const [subscription, publicCampaign] = approval.campaigns;
  await worker.enqueue(subscription.id);
  const before = (await db.subscriptionReminder.findMany()).map(r => r.id).sort();
  assert.equal(before.length, 4);
  await assert.rejects(narrowApprovedScope(db, now));
  await appendApprovedRenewal(db, now);
  await worker.enqueue(subscription.id);
  assert.deepEqual((await db.subscriptionReminder.findMany()).map(r => r.id).sort(), before);
  await narrowApprovedScope(db, now);
  assert.equal(calls.length, 0);
  const cancelledIds = (await db.subscriptionReminder.findMany({ where: { status: "CANCELLED" } })).map(r => r.id).sort();
  assert.equal(cancelledIds.length, 2);
  await worker.run(subscription.id); assert.equal(calls.length, 2);
  await worker.run(subscription.id); assert.equal(calls.length, 2);
  await worker.run(publicCampaign.id); assert.equal(calls.length, 4);
  const sent = await approvedSummary(db);
  assert.equal(sent.deliveries.filter(r => r.status === "SENT").length, 4);
  assert.ok(sent.deliveries.every(r => r.receiptConfirmedAt === null));
  assert.ok(sent.campaigns.every(c => c.dispatches === 2 && c.lastSuccessAt));
  assert.ok(calls.slice(2).every(c => c.text.includes("VOLUNTARY") && c.text.includes("2026-10-01T10:00:00.000Z")));
  const expectedEmails = [approval.owner.email, approval.operators[0].email].sort();
  assert.deepEqual(calls.slice(0, 2).map(c => c.recipient).sort(), expectedEmails);
  assert.deepEqual(calls.slice(2).map(c => c.recipient).sort(), expectedEmails);
  for (const campaign of approval.campaigns) await worker.run(campaign.id);
  assert.equal(calls.length, 4);
  assert.deepEqual((await approvedSummary(db)).attempts, sent.attempts);
  assert.deepEqual((await db.subscriptionReminder.findMany({ where: { status: "CANCELLED" } })).map(r => r.id).sort(), cancelledIds);
  assert.equal(await db.subscriptionPaidPeriod.count({ where: { paymentKind: "SIMULATED_PAYMENT" } }), 2);
});
